"""
Django settings for myBBS project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_(mge-8uwbz%ez*ku$6pv2jc(-)6n$tv=!zj7vl9aohk($@ioe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # django-guardian模块
    'guardian',
    #myCustomize
    'myauth.apps.MyauthConfig',
    'myarticle.apps.MyarticleConfig',
    # 添加ckeditor富文本编辑器
    'ckeditor',
    # ckeditor的图片上传功能
    'ckeditor_uploader'


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myBBS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myBBS.wsgi.application'
#######################################################################
##########################django-guardian设置###########################
#######################################################################

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend', # this is default
    'guardian.backends.ObjectPermissionBackend',
)

GUARDIAN_RAISE_403 = True
GUARDIAN_GET_INIT_ANONYMOUS_USER = 'myauth.models.get_custom_anon_user'
# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#######################################################################
##########################数据库设置###################################
#######################################################################
DATABASES = {
    'default': {

        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mybbs_dev',
        'USER': 'root',
        'PASSWORD': 'wqn641214',
        'HOST': '172.16.207.119',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True
# 设置USE_TZ = False, TIME_ZONE = 'Asia/Shanghai', 则使用上海的UTC时间
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
#######################################################################
##########################静态文件设置#################################
#######################################################################
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
#静态资源的url
STATIC_URL ='/static/'
#正式环境部署时，所有静态资源的位置
STATIC_ROOT = os.path.join(BASE_DIR,'myAllStatic/')
#开发时，通用静态资源的位置
STATICFILES_DIRS=(
    os.path.join(BASE_DIR,"static/"),
)

# 配置 MEDIA_URL 作为公用 URL，指向上传文件的基本路径
MEDIA_URL = '/media/'
# 配置 MEDIA_ROOT 作为你上传文件在服务器中的基本路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'myUpload') # 注意此处不要写成列表或元组的形式
# 配置 MEDIA_URL 作为公用 URL，指向上传文件的基本路径

#######################################################################
##########################设置session#################################
#######################################################################
# SESSION_COOKIE_AGE =10*60# 设置过期时间10分钟，默认为两周
# SESSION_SAVE_EVERY_REQUEST = True
# SESSION_EXPIRE_AT_BROWSER_CLOSE =True# 设置关闭浏览器时失效


#######################################################################
###################### logging日志配置#################################
#######################################################################
LOG_DIR = os.path.join(BASE_DIR, 'myLog')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {# 日志格式
        'standard': {
            'format': '%(asctime)s [%(threadName)s:%(thread)d] '
                        '[%(funcName)s:%(lineno)d] [%(levelname)s]- %(message)s'
                      # '[%(pathname)s:%(funcName)s:%(lineno)d] [%(levelname)s]- %(message)s'
        },
        'simple': {
            'format': '%(asctime)s %(message)s'
        }
    },
    'filters': {# 过滤器
        'test':{
            '()': 'myBBS.config.myLogFilter.TestFilter'
        }
    },
    'handlers': {# 处理器
        'null': {
            'level': 'DEBUG',
            'class': 'logging.NullHandler',
        },
        'error_handler': {# error内容输出到另外的文件
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR,'error.log'),#日志输出文件
            'maxBytes':1024*1024*1,#文件大小
            'backupCount': 5,#备份份数
            'formatter':'standard',#使用哪种formatters日志格式
            'encoding': 'utf8',
        },
        'file_handler': {# 记录到日志文件(需要创建对应的目录，否则会出错)
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR,'service.log'),# 日志输出文件
            'maxBytes':1024*1024*1,#文件大小
            'backupCount': 5,#备份份数
            'formatter':'standard',#使用哪种formatters日志格式
            'encoding': 'utf8',
        },
        'console_handler':{# 输出到控制台
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'statistics_handler':{
            'level':'DEBUG',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR,'statistics.log'),
            'maxBytes':1024*1024*5,
            'backupCount': 5,
            'formatter':'simple',
            'encoding': 'utf8',
        }
    },
    'loggers': {# logging管理器
        'django': {
            # 'handlers': ['console_handler', 'file_handler', 'error_handler'],
            'handlers': ['console_handler', 'file_handler'],
            'filters': ['test'],
            'level': 'DEBUG'
        },
        'statistics': {
            'handlers': ['statistics_handler'],
            'level': 'DEBUG'
        }
    }
}

#######################################################################
########################### 认证登陆相关#################################
#######################################################################
LOGIN_URL = '/myAuth/login/'#设置默认的登陆页面，默认会跳转到‘/accounts/login/’
# 告诉Django项目用哪张表做认证
AUTH_USER_MODEL = 'myauth.MyUserInfo'

#######################################################################
##########################ckeditor配置#################################
#######################################################################
from ckeditor.configs import DEFAULT_CONFIG

CKEDITOR_UPLOAD_PATH = "ckeditorUpload/"
if not os.path.exists(CKEDITOR_UPLOAD_PATH):
    os.makedirs(CKEDITOR_UPLOAD_PATH)

# enable thumbnails in ckeditor gallery.
CKEDITOR_IMAGE_BACKEND = "pillow"
'''
With the pillow backend, you can change the thumbnail size with the CKEDITOR_THUMBNAIL_SIZE setting (formerly THUMBNAIL_SIZE). Default value: (75, 75)
'''
CKEDITOR_THUMBNAIL_SIZE = (300, 300)
CKEDITOR_IMAGE_QUALITY = 40
'''
show directories on the "Browse Server" page. This enables image grouping by directory they are stored in, sorted by date.
'''
CKEDITOR_BROWSE_SHOW_DIRS = True
CKEDITOR_ALLOW_NONIMAGE_FILES = True

CUSTOM_TOOLBAR = [
    {
        "name": "document",
        "items": [
            "Styles", "Format", "Bold", "Italic", "Underline", "Strike", "-",
            "TextColor", "BGColor",  "-",
            "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock",
        ],
    },
    {
        "name": "widgets",
        "items": [
            "Undo", "Redo", "-",
            "NumberedList", "BulletedList", "-",
            "Outdent", "Indent", "-",
            "Link", "Unlink", "-",
            "Image", "CodeSnippet", "Table", "HorizontalRule", "Smiley", "SpecialChar", "-",
            "Blockquote", "-",
            "ShowBlocks", "Maximize",
        ],
    },
]


# ckeditor配置



CKEDITOR_CONFIGS = {
    # "default": DEFAULT_CONFIG,
    'default': {
        'toolbar': 'full',  # 工具栏全部功能
        'height': 300,  # 高度
        'width': '100%',  # 宽度
        'uiColor' : '#E0F2F4',
        "codeSnippet_theme": "school_book",
    },
    "my-custom-toolbar": {
        'width': '100%',  # 宽度
        'uiColor' : '#E0F2F4',
        "skin": "moono-lisa",
        "toolbar": CUSTOM_TOOLBAR,
        "toolbarGroups": None,
        # "extraPlugins": ",".join(["image2", "codesnippet"]),
        # "removePlugins": ",".join(["image"]),
        "codeSnippet_theme": "school_book",
    },
}


