# Generated by Django 2.2 on 2020-02-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myarticle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article2tag',
            options={'verbose_name': '文章-标签对照', 'verbose_name_plural': '文章-标签对照'},
        ),
    ]
