# Generated by Django 2.2 on 2020-01-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuserinfo',
            name='avatar',
            field=models.ImageField(default='myImage/default.png', upload_to='avatars/', verbose_name='头像'),
        ),
    ]
